watch_stylesheet: true
watch_config: true
debug: false
update_check: true

# komorebi:
#   start_command: "komorebic start --whkd"
#   stop_command: "komorebic stop --whkd"
#   reload_command: "komorebic reload-configuration"

bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: "None"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 2
      left: 2
      bottom: 2
      right: 2
    widgets:
      left:
        # - "komorebi_active_layout"
        # - "komorebi_workspaces"
        - "glazewm_tiling_direction"
        - "glazewm_workspaces"
        # - "systray"
        - "cpu"
        - "memory"
        - "traffic"
      center: 
        - "clock"
      right:
        - "active_window"
        - "weather"
        - "volume"
        # - "media"
        - "notifications"

widgets:
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\ue950</span> {info[percent][total]}%"
      label_alt: "{info[histograms][cpu_percent]}"
      update_interval: 1000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_cpu_menu"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span class='download'>\uea9a {download_speed}</span>|<span class='upload'>{upload_speed} \ueaa1</span>"
      update_interval: 1000
      menu:
        round_corners: false
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "toggle_menu"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  # komorebi_active_layout:
  #   type: "komorebi.active_layout.ActiveLayoutWidget"
  #   options:
  #     hide_if_offline: true
  #     label: "{icon}"
  #     layouts:
  #       - "bsp"
  #       - "columns"
  #       - "rows"
  #       - "grid"
  #       - "scrolling"
  #       - "vertical_stack"
  #       - "horizontal_stack"
  #       - "ultrawide_vertical_stack"
  #       - "right_main_vertical_stack"
  #     layout_icons:
  #       bsp: "\uebeb"
  #       columns: "\uebf7"
  #       rows: "\uec01"
  #       grid: "\udb81\udf58"
  #       scrolling: "\uebf7"
  #       vertical_stack: "\uebee"
  #       horizontal_stack: "\uebf0"
  #       ultrawide_vertical_stack: "\uebee"
  #       right_main_vertical_stack: "\uebf1"
  #       monocle: "\uf06f"
  #       maximized: "\uf06f"
  #       floating: "\uf2d2"
  #       paused: "\udb83\udf89"
  #       tiling: "\udb81\ude40"
  #     callbacks:
  #       on_left: "toggle_layout_menu"
  #       on_middle: "toggle_tiling"
  #       on_right: "next_layout"
  #     layout_menu:
  #       blur: true
  #       round_corners: false
  #       alignment: "left"
  #       direction: "down"
  #       offset_top: true
  #       show_layout_icons: true
  #     container_padding:
  #       top: 0
  #       left: 0
  #       bottom: 0
  #       right: 0
  #     label_shadow:
  #       enabled: true
  #       color: "black"
  #       radius: 5
  #       offset: [0, 0]

  # komorebi_workspaces:
  #   type: "komorebi.workspaces.WorkspaceWidget"
  #   options:
  #     label_offline: "<span>\ueb96</span>"
  #     label_default_name: ""
  #     label_zero_index: false
  #     hide_empty_workspaces: true
  #     hide_if_offline: true
  #     container_padding:
  #       top: 0
  #       left: 0
  #       bottom: 0
  #       right: 0
  #     label_shadow:
  #       enabled: true
  #       color: "black"
  #       radius: 5
  #       offset: [0, 0]

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[process][name]} | {win[class_name]}"
      label_icon: false
      label_icon_size: 16
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: false
      animation:
        enabled: false
        duration: 200
        type: "fadeInOut"
      rewrite:
        - pattern: "Visual Studio Code"
          replacement: "VSC"
      ignore_window:
        classes: []
        processes: []
        titles:
          - Task Switching
          - Magnifier
          - Notification Center
          - Raycast
          - Windows Shell Experience Host
          - Shut Down Windows
          - Delete File
          - Delete Folder
          - Delete Shortcut
          - Delete Multiple Items
      callbacks:
        on_left: "do_nothing"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  # media:
  #   type: "yasb.media.MediaWidget"
  #   options:
  #     label: "{title}"
  #     label_alt: "{artist}"
  #     callbacks:
  #       on_left: "toggle_media_menu"
  #       on_middle: "toggle_play_pause"
  #       on_right: "toggle_label"
  #     max_field_size:
  #       label: 60
  #       label_alt: 60
  #     hide_empty: true
  #     show_thumbnail: false
  #     scrolling_label:
  #       enabled: false
  #       update_interval_ms: 33
  #       ease_slope: 20
  #       ease_pos: 0.8
  #       ease_min: 0.5
  #     icons:
  #       prev_track: "\ue892"
  #       next_track: "\ue893"
  #       play: "\ue768"
  #       pause: "\ue769"
  #     media_menu:
  #       blur: true
  #       round_corners: false
  #       round_corners_type: "normal"
  #       border_color: "system"
  #       alignment: "center"
  #       direction: "down"
  #       offset_top: true
  #       thumbnail_corner_radius: 6
  #       thumbnail_size: 100
  #       max_title_size: 40
  #       max_artist_size: 20
  #       show_source: true
  #   icons:
  #       play: "\ue768"
  #       pause: "\ue769"
  #       prev_track: "\ue892"
  #       next_track: "\ue893"
  #   container_padding:
  #     top: 0
  #     left: 0
  #     bottom: 0
  #     right: 0
  #   label_shadow:
  #      enabled: true
  #      color: "black"
  #      radius: 5
  #      offset: [0, 0]

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ued59"
      label_expanded: "\ue77c"
      show_unpinned: false
      show_unpinned_button: false
      show_battery: false
      show_volume: false
      show_network: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      container_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "Low: {min_temp} | High: {max_temp} | Humidity: {humidity}"
      api_key: env # Get your free API key from https://www.weatherapi.com/
      show_alerts: true
      update_interval: 600
      hide_decimal: true
      units: "imperial"
      location: env
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue302"
        cloudyNight: "\ue32e"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\ue35f"
        blizzardNight: "\ue360"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: false
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        icon_size: 40
        offset_top: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%A %H:%M:%S}"
      # label_alt: "{%A, %d %B %Y}"
      update_interval: 100
      calendar:
        blur: true
        round_corners: false
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>{level}"
      volume_icons:
        - "\ue74f" # Icon for muted
        - "\ue992" # Icon for 0-10% volume
        - "\ue993" # Icon for 11-30% volume
        - "\ue994" # Icon for 31-60% volume
        - "\ue995" # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: false
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: true
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\udb80\udf9f</span>{count}"
      label_alt: "{count} Notification(s)"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_middle: "clear_notifications"
        on_right: "toggle_label"
      container_padding:
        top: 0
        left: 10
        bottom: 0
        right: 10
      label_shadow:
        enabled: true
        color: "black"
        radius: 5
        offset: [0, 0]
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      enable_scroll_switching: true
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      app_icons: 
        enabled_populated: false
        enabled_active: false
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      animation: false

      # By default workspace names are fetched from GlazeWM and "display_name" option takes priority over "name".
      # However, you can customize populated and empty labels here using {name} and {display_name} placeholders if needed.
      # {name} will be replaced with workspace name (index) from GlazeWM.
      # {display_name} will be replaced with workspace display_name from GlazeWM.

      # populated_label: "{name} {display_name} \uebb4"
      # empty_label: "{name} {display_name} \uebb5"